name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Installing Tree
      run: sudo apt-get install tree
    - name: Showing Tree
      run: tree -L 4
    - name: npm install
      run: npm install
      env:
        NPM_AUTH_TOKEN: ${{ secrets.TEST }}
